TARGETS=\
    data/area/abertawe-swansea.geojson\
    data/area/adur.geojson\
    data/area/allerdale.geojson\
    data/area/amber-valley.geojson\
    data/area/arun.geojson\
    data/area/ashfield.geojson\
    data/area/ashford.geojson\
    data/area/aylesbury-vale.geojson\
    data/area/babergh.geojson\
    data/area/barking-and-dagenham.geojson\
    data/area/barnet.geojson\
    data/area/barnsley.geojson\
    data/area/barrow-in-furness.geojson\
    data/area/basildon.geojson\
    data/area/basingstoke-and-deane.geojson\
    data/area/bassetlaw.geojson\
    data/area/bath-and-north-east-somerset.geojson\
    data/area/bedford.geojson\
    data/area/bexley.geojson\
    data/area/birmingham.geojson\
    data/area/blaby.geojson\
    data/area/blackburn-with-darwen.geojson\
    data/area/blackpool.geojson\
    data/area/blaenau-gwent-blaenau-gwent.geojson\
    data/area/bolsover.geojson\
    data/area/bolton.geojson\
    data/area/boston.geojson\
    data/area/bournemouth.geojson\
    data/area/bracknell-forest.geojson\
    data/area/bradford.geojson\
    data/area/braintree.geojson\
    data/area/breckland.geojson\
    data/area/brent.geojson\
    data/area/brentwood.geojson\
    data/area/broadland.geojson\
    data/area/bromley.geojson\
    data/area/bromsgrove.geojson\
    data/area/broxbourne.geojson\
    data/area/broxtowe.geojson\
    data/area/burnley.geojson\
    data/area/bury.geojson\
    data/area/caerdydd-cardiff.geojson\
    data/area/caerffili-caerphilly.geojson\
    data/area/calderdale.geojson\
    data/area/cambridge.geojson\
    data/area/camden.geojson\
    data/area/cannock-chase.geojson\
    data/area/canterbury.geojson\
    data/area/carlisle.geojson\
    data/area/casnewydd-newport.geojson\
    data/area/castell-nedd-port-talbot-neath-port-talbot.geojson\
    data/area/castle-point.geojson\
    data/area/central-bedfordshire.geojson\
    data/area/charnwood.geojson\
    data/area/chelmsford.geojson\
    data/area/cheltenham.geojson\
    data/area/cherwell.geojson\
    data/area/cheshire-east.geojson\
    data/area/cheshire-west-and-chester.geojson\
    data/area/chesterfield.geojson\
    data/area/chichester.geojson\
    data/area/chiltern.geojson\
    data/area/chorley.geojson\
    data/area/christchurch.geojson\
    data/area/city-of-bristol.geojson\
    data/area/city-of-derby.geojson\
    data/area/city-of-kingston-upon-hull.geojson\
    data/area/city-of-leicester.geojson\
    data/area/city-of-london.geojson\
    data/area/city-of-nottingham.geojson\
    data/area/city-of-peterborough.geojson\
    data/area/city-of-plymouth.geojson\
    data/area/city-of-portsmouth.geojson\
    data/area/city-of-southampton.geojson\
    data/area/city-of-stoke-on-trent.geojson\
    data/area/city-of-westminster.geojson\
    data/area/city-of-wolverhampton.geojson\
    data/area/colchester.geojson\
    data/area/conwy-conwy.geojson\
    data/area/copeland.geojson\
    data/area/corby.geojson\
    data/area/cornwall.geojson\
    data/area/cotswold.geojson\
    data/area/county-durham.geojson\
    data/area/county-of-herefordshire.geojson\
    data/area/coventry.geojson\
    data/area/craven.geojson\
    data/area/crawley.geojson\
    data/area/croydon.geojson\
    data/area/dacorum.geojson\
    data/area/darlington.geojson\
    data/area/dartford.geojson\
    data/area/daventry.geojson\
    data/area/derbyshire-dales.geojson\
    data/area/doncaster.geojson\
    data/area/dover.geojson\
    data/area/dudley.geojson\
    data/area/ealing.geojson\
    data/area/east-cambridgeshire.geojson\
    data/area/east-devon.geojson\
    data/area/east-dorset.geojson\
    data/area/east-hampshire.geojson\
    data/area/east-hertfordshire.geojson\
    data/area/east-lindsey.geojson\
    data/area/east-northamptonshire.geojson\
    data/area/east-riding-of-yorkshire.geojson\
    data/area/east-staffordshire.geojson\
    data/area/eastbourne.geojson\
    data/area/eastleigh.geojson\
    data/area/eden.geojson\
    data/area/elmbridge.geojson\
    data/area/enfield.geojson\
    data/area/epping-forest.geojson\
    data/area/epsom-and-ewell.geojson\
    data/area/erewash.geojson\
    data/area/exeter.geojson\
    data/area/fareham.geojson\
    data/area/fenland.geojson\
    data/area/forest-heath.geojson\
    data/area/forest-of-dean.geojson\
    data/area/fylde.geojson\
    data/area/gateshead.geojson\
    data/area/gedling.geojson\
    data/area/gloucester.geojson\
    data/area/gosport.geojson\
    data/area/gravesham.geojson\
    data/area/great-yarmouth.geojson\
    data/area/greenwich.geojson\
    data/area/guildford.geojson\
    data/area/gwynedd-gwynedd.geojson\
    data/area/hackney.geojson\
    data/area/halton.geojson\
    data/area/hambleton.geojson\
    data/area/hammersmith-and-fulham.geojson\
    data/area/harborough.geojson\
    data/area/haringey.geojson\
    data/area/harlow.geojson\
    data/area/hartlepool.geojson\
    data/area/harrogate.geojson\
    data/area/harrow.geojson\
    data/area/hart.geojson\
    data/area/hastings.geojson\
    data/area/havant.geojson\
    data/area/havering.geojson\
    data/area/hertsmere.geojson\
    data/area/high-peak.geojson\
    data/area/hillingdon.geojson\
    data/area/hinckley-and-bosworth.geojson\
    data/area/horsham.geojson\
    data/area/hounslow.geojson\
    data/area/huntingdonshire.geojson\
    data/area/hyndburn.geojson\
    data/area/ipswich.geojson\
    data/area/isle-of-wight.geojson\
    data/area/isles-of-scilly.geojson\
    data/area/islington.geojson\
    data/area/kensington-and-chelsea.geojson\
    data/area/kettering.geojson\
    data/area/kings-lynn-and-west-norfolk.geojson\
    data/area/kingston-upon-thames.geojson\
    data/area/kirklees.geojson\
    data/area/knowsley.geojson\
    data/area/lambeth.geojson\
    data/area/lancaster.geojson\
    data/area/leeds.geojson\
    data/area/lewes.geojson\
    data/area/lewisham.geojson\
    data/area/lichfield.geojson\
    data/area/lincoln.geojson\
    data/area/liverpool.geojson\
    data/area/luton.geojson\
    data/area/maidstone.geojson\
    data/area/maldon.geojson\
    data/area/malvern-hills.geojson\
    data/area/manchester.geojson\
    data/area/mansfield.geojson\
    data/area/medway.geojson\
    data/area/melton.geojson\
    data/area/mendip.geojson\
    data/area/merthyr-tudful-merthyr-tydfil.geojson\
    data/area/merton.geojson\
    data/area/mid-devon.geojson\
    data/area/mid-suffolk.geojson\
    data/area/mid-sussex.geojson\
    data/area/middlesbrough.geojson\
    data/area/milton-keynes.geojson\
    data/area/mole-valley.geojson\
    data/area/new-forest.geojson\
    data/area/newark-and-sherwood.geojson\
    data/area/newcastle-under-lyme.geojson\
    data/area/newcastle-upon-tyne.geojson\
    data/area/newham.geojson\
    data/area/north-devon.geojson\
    data/area/north-dorset.geojson\
    data/area/north-east-derbyshire.geojson\
    data/area/north-east-lincolnshire.geojson\
    data/area/north-hertfordshire.geojson\
    data/area/north-kesteven.geojson\
    data/area/north-lincolnshire.geojson\
    data/area/north-norfolk.geojson\
    data/area/north-somerset.geojson\
    data/area/north-tyneside.geojson\
    data/area/north-warwickshire.geojson\
    data/area/north-west-leicestershire.geojson\
    data/area/northampton.geojson\
    data/area/northumberland.geojson\
    data/area/norwich.geojson\
    data/area/nuneaton-and-bedworth.geojson\
    data/area/oadby-and-wigston.geojson\
    data/area/oldham.geojson\
    data/area/oxford.geojson\
    data/area/pendle.geojson\
    data/area/pen-y-bont-ar-ogwr-bridgend.geojson\
    data/area/preston.geojson\
    data/area/poole.geojson\
    data/area/powys-powys.geojson\
    data/area/purbeck.geojson\
    data/area/reading.geojson\
    data/area/redbridge.geojson\
    data/area/redcar-and-cleveland.geojson\
    data/area/redditch.geojson\
    data/area/reigate-and-banstead.geojson\
    data/area/rhondda-cynon-taf-rhondda-cynon-taf.geojson\
    data/area/ribble-valley.geojson\
    data/area/richmond-upon-thames.geojson\
    data/area/richmondshire.geojson\
    data/area/rochdale.geojson\
    data/area/rochford.geojson\
    data/area/rossendale.geojson\
    data/area/rother.geojson\
    data/area/rotherham.geojson\
    data/area/rugby.geojson\
    data/area/runnymede.geojson\
    data/area/rushcliffe.geojson\
    data/area/rushmoor.geojson\
    data/area/rutland.geojson\
    data/area/ryedale.geojson\
    data/area/salford.geojson\
    data/area/sandwell.geojson\
    data/area/scarborough.geojson\
    data/area/sedgemoor.geojson\
    data/area/sefton.geojson\
    data/area/selby.geojson\
    data/area/sevenoaks.geojson\
    data/area/sheffield.geojson\
    data/area/shepway.geojson\
    data/area/shropshire.geojson\
    data/area/sir-benfro-pembrokeshire.geojson\
    data/area/sir-ceredigion-ceredigion.geojson\
    data/area/sir-ddinbych-denbighshire.geojson\
    data/area/sir-fynwy-monmouthshire.geojson\
    data/area/sir-gaerfyrddin-carmarthenshire.geojson\
    data/area/sir-y-fflint-flintshire.geojson\
    data/area/sir-ynys-mon-isle-of-anglesey.geojson\
    data/area/slough.geojson\
    data/area/solihull.geojson\
    data/area/south-bucks.geojson\
    data/area/south-cambridgeshire.geojson\
    data/area/south-derbyshire.geojson\
    data/area/south-gloucestershire.geojson\
    data/area/south-hams.geojson\
    data/area/south-holland.geojson\
    data/area/south-kesteven.geojson\
    data/area/south-lakeland.geojson\
    data/area/south-norfolk.geojson\
    data/area/south-northamptonshire.geojson\
    data/area/south-oxfordshire.geojson\
    data/area/south-ribble.geojson\
    data/area/south-somerset.geojson\
    data/area/south-staffordshire.geojson\
    data/area/south-tyneside-district.geojson\
    data/area/southend-on-sea.geojson\
    data/area/southwark.geojson\
    data/area/spelthorne.geojson\
    data/area/st-albans.geojson\
    data/area/st-edmundsbury.geojson\
    data/area/st-helens.geojson\
    data/area/stafford.geojson\
    data/area/staffordshire-moorlands.geojson\
    data/area/stevenage.geojson\
    data/area/stockport.geojson\
    data/area/stockton-on-tees.geojson\
    data/area/stratford-on-avon.geojson\
    data/area/stroud.geojson\
    data/area/suffolk-coastal.geojson\
    data/area/sunderland.geojson\
    data/area/surrey-heath.geojson\
    data/area/sutton.geojson\
    data/area/swale.geojson\
    data/area/swindon.geojson\
    data/area/tameside.geojson\
    data/area/tamworth.geojson\
    data/area/tandridge.geojson\
    data/area/taunton-deane.geojson\
    data/area/teignbridge.geojson\
    data/area/telford-and-wrekin.geojson\
    data/area/tendring.geojson\
    data/area/test-valley.geojson\
    data/area/tewkesbury.geojson\
    data/area/thanet.geojson\
    data/area/the-city-of-brighton-and-hove.geojson\
    data/area/three-rivers.geojson\
    data/area/thurrock.geojson\
    data/area/tonbridge-and-malling.geojson\
    data/area/tor-faen-torfaen.geojson\
    data/area/torbay.geojson\
    data/area/torridge.geojson\
    data/area/tower-hamlets.geojson\
    data/area/trafford.geojson\
    data/area/tunbridge-wells.geojson\
    data/area/uttlesford.geojson\
    data/area/vale-of-glamorgan.geojson\
    data/area/vale-of-white-horse.geojson\
    data/area/wakefield.geojson\
    data/area/walsall.geojson\
    data/area/waltham-forest.geojson\
    data/area/wandsworth.geojson\
    data/area/warrington.geojson\
    data/area/warwick.geojson\
    data/area/watford.geojson\
    data/area/waveney.geojson\
    data/area/waverley.geojson\
    data/area/wealden.geojson\
    data/area/wellingborough.geojson\
    data/area/welwyn-hatfield.geojson\
    data/area/west-berkshire.geojson\
    data/area/west-devon.geojson\
    data/area/west-dorset.geojson\
    data/area/west-lancashire.geojson\
    data/area/west-lindsey.geojson\
    data/area/west-oxfordshire.geojson\
    data/area/west-somerset.geojson\
    data/area/weymouth-and-portland.geojson\
    data/area/wigan.geojson\
    data/area/wiltshire.geojson\
    data/area/winchester.geojson\
    data/area/windsor-and-maidenhead.geojson\
    data/area/wirral.geojson\
    data/area/woking.geojson\
    data/area/wokingham.geojson\
    data/area/worcester.geojson\
    data/area/worthing.geojson\
    data/area/wrecsam-wrexham.geojson\
    data/area/wychavon.geojson\
    data/area/wycombe.geojson\
    data/area/wyre-forest.geojson\
    data/area/wyre.geojson\
    data/area/york.geojson
